### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by saemarp** [xander1998/spikestrips#1]
Hey,

Went to do training with some people tonight and the strips no longer work on the server. Not sure if it is from a fivem update or if it is a resource we have loaded. Just thought I would tell you.

Mark C.

PS This is the same guy who helped you test them on your server.

**Comment by xander1998** [comment]
Hm. Thank You. They have been buggy since release just haven't had a whole lot of time to improve on my resources.

**Comment by saemarp** [comment]
Well, with your big project coming out soon I am not surprised you have been busy. Still look forward to seeing the CAD and your future releases.
