### ISSUE TITLE
Spawn spikes

### ISSUE THREAD

**Issue by madalton** [xander1998/spikestrips#2]
hi,

sry for my bad english i m french. I don't have succes spawn spike. is on chat message ? when i pressed on keyboard ?

**Comment by madalton** [comment]
sry i have check this => https://forum.fivem.net/t/release-stinger-strips/67690  is ok thx for all

**Comment by xander1998** [comment]
You need to be one of the ped models in the config.lua

`SpikeConfig.PedsList = {
	"s_m_y_cop_01",
	"s_f_y_cop_01",
	"s_m_y_hwaycop_01",
	"s_m_y_sheriff_01",
	"s_f_y_sheriff_01",
	"s_m_y_swat_01",
	"s_m_y_ranger_01",
	"s_f_y_ranger_01"
}`
