### ISSUE TITLE
Spikes not popping tires?

### ISSUE THREAD

**Issue by WolfCrisis** [xander1998/spikestrips#3]
The spikes will set and remove just fine, they just wont actually pop tires when someone drives on them.

**Comment by xander1998** [comment]
the fivem update might have broke them. have they ever worked or do they ever work or is it just something thats never worked at all.. other then spawnijg of course.

**Comment by WolfCrisis** [comment]
They worked before the Fivem update.

**Comment by xander1998** [comment]
great... lol I will have to find a fix for it then. Thanks for telling me.
